@echo off
echo Installing dependencies...
call .\.venv\Scripts\pip install -r requirements.txt
echo Generating Mock Data...
call .\.venv\Scripts\python mock_data.py
echo Ingesting Knowledge Base into Chroma DB...
call .\.venv\Scripts\python ingest.py
echo Starting Gradio Application...
call .\.venv\Scripts\python app.py
